ASR1/urls.py
from django.urls import path
from ASR1 import views

urlpatterns = [
    path('', views.form, name='request'),
    path('users/', views.users, name='users')
]

ASR2/urls.py
from django.urls import path
from ASR2 import views

urlpatterns = [
    path('', views.deployment, name='deployment'),
]

BancoAlpes/urls.py
from django.contrib import admin
from django.urls import include, path
from BancoAlpes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('health/', views.health, name='health'),
    path('request/', include('ASR1.urls')),
    path('deployment/', include('ASR2.urls'))
]

ASR1/models.py
from django.db import models
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization

class DatosPersonales(models.Model):
    nombres = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=30)
    pais = models.CharField(max_length=15)
    ciudad = models.CharField(max_length=20)
    numero = models.CharField(max_length=10)
    email = models.EmailField()
    firma = models.TextField()

class SignatureKeys(models.Model):
    privateKey = models.TextField()
    publicKey = models.TextField()

    @classmethod
    def create(cls):
        privateKey = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend()
        )
        publicKey = privateKey.public_key()
        pemPrivateKey = privateKey.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        ).decode('utf-8')
        pemPublicKey = publicKey.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ).decode('utf-8')
        return cls(privateKey=pemPrivateKey, publicKey=pemPublicKey)

ASR2/models.py
from django.db import models

class Instance(models.Model):
    instance = models.CharField(max_length=25)

ASR1/forms.py
from django import forms
from .models import DatosPersonales

class DatosPersonalesForm(forms.ModelForm):
    class Meta:
        model = DatosPersonales
        fields = ['nombres', 'apellidos', 'pais', 'ciudad', 'numero', 'email']

ASR1/views.py
from django.shortcuts import render

from ASR1.logic.ASR5 import generateSignature, verifySignature
from ASR1.models import DatosPersonales
from .forms import DatosPersonalesForm
from .logic.producer import sendRequest

def form(request):
    if request.method == "POST":
        form = DatosPersonalesForm(request.POST)
        if form.is_valid():
            newData = form.save(commit=False)
            dataToSign = f"{newData.nombres}{newData.apellidos}{newData.pais}{newData.ciudad}57{newData.numero}{newData.email}"
            newData.firma = generateSignature(dataToSign)
            newData.save()
            sendRequest(form.cleaned_data)
            return render(request, "ASR1/check.html")
        else:
            print(form.errors)
    else:
        form = DatosPersonalesForm()
    return render(request, "ASR1/form.html", {'form': form})

def users(request):
    users = DatosPersonales.objects.all()
    for user in users:
        user.state = verifySignature(f"{user.nombres}{user.apellidos}{user.pais}{user.ciudad}57{user.numero}{user.email}", user.firma)
    return render(request, "ASR1/users.html", {'users': users})

ASR2/views.py
import threading
import time
from django.shortcuts import redirect, render
from googleapiclient import discovery
from google.oauth2 import service_account
import os
from django.conf import settings
from ASR2.logic.producer import sendRequest
from deployment import turnOffApp

credentials_path = os.path.join(settings.BASE_DIR, 'ASR2', 'static', 'json', 'credentials.json')
credentials = service_account.Credentials.from_service_account_file(credentials_path)
service = discovery.build('compute', 'v1', credentials=credentials)

def delayedAction():
    time.sleep(120)
    sendRequest({'Action': 'Restart Load Balancer'})

def deployment(request):
    instances = {}
    for instance in 'abcd':
        instanceName = f'banco-alpes-{instance}'
        instances[instance] = getInstanceStatus(instanceName)['status']

    if request.method == 'POST':
        instance = request.POST.get('instance')
        if instance == 'turn-off':
            turnOffApp()
        elif instances[instance[-1]] == 'RUNNING':
            stopInstance(instance)
            threading.Thread(target=delayedAction).start()
        else:
            startInstance(instance)
            threading.Thread(target=delayedAction).start()
        return redirect('deployment')
    return render(request, 'ASR2/deployment.html', context={'instances': instances})

def startInstance(instanceName):
    req = service.instances().start(project='arquisoft-202410', zone='us-central1-a', instance=instanceName)
    response = req.execute()
    return response

def getInstanceStatus(instanceName):
    req = service.instances().get(project='arquisoft-202410', zone='us-central1-a', instance=instanceName)
    response = req.execute()
    return response

def stopInstance(instanceName):
    req = service.instances().stop(project='arquisoft-202410', zone='us-central1-a', instance=instanceName)
    response = req.execute()
    return response

BancoAlpes/views.py
from django.http import JsonResponse
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def health(request):
    return JsonResponse({'status': 'ok'}, status=200)

ASR1/templates/ASR1/check.html
{% extends "app.html" %}

{% block css %}
<link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
<style>
  .otpCheck {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  :where(.container, .container form, .input-field, header) {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  .container {
    background: #fff;
    padding: 30px 65px;
    border-radius: 12px;
    row-gap: 20px;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
  }
  .container header {
    height: 65px;
    width: 65px;
    background: #f1791f;
    color: #fff;
    font-size: 2.5rem;
    border-radius: 50%;
  }
  .container h4 {
    font-size: 1.25rem;
    color: #333;
    font-weight: 500;
  }
  form .input-field {
    flex-direction: row;
    column-gap: 10px;
  }
  .input-field input {
    height: 45px;
    width: 42px;
    border-radius: 6px;
    outline: none;
    font-size: 1.125rem;
    text-align: center;
    border: 1px solid #ddd;
  }
  .input-field input:focus {
    box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1);
  }
  .input-field input::-webkit-inner-spin-button,
  .input-field input::-webkit-outer-spin-button {
    display: none;
  }
  .checkButton {
    margin-top: 25px;
    width: 100%;
    color: #fff;
    font-size: 1rem;
    border: none;
    padding: 9px 0;
    cursor: pointer;
    border-radius: 6px;
    pointer-events: none;
    background: #f4ca9f;
    transition: all 0.2s ease;
  }
  .checkButton.active {
    background: #f2872f;
    pointer-events: auto;
  }
  .checkButton:hover {
    background: #f2872f;
  }
</style>
{% endblock %}

{% block js %}
<script>
  localStorage.clear();

  const inputs = document.querySelectorAll(".input-field input"),
  button = document.querySelector(".checkButton");

  inputs.forEach((input, index1) => {
    input.addEventListener("keyup", (e) => {
      const currentInput = input,
      nextInput = input.nextElementSibling,
      prevInput = input.previousElementSibling;
      if (currentInput.value.length > 1) {
        currentInput.value = "";
        return;
      }
      if (nextInput && nextInput.hasAttribute("disabled") && currentInput.value !== "") {
        nextInput.removeAttribute("disabled");
        nextInput.focus();
      }
      if (e.key === "Backspace") {
        inputs.forEach((input, index2) => {
          if (index1 <= index2 && prevInput) {
            input.setAttribute("disabled", true);
            input.value = "";
            prevInput.focus();
          }
        });
      }
      if (!inputs[3].disabled && inputs[3].value !== "") {
        button.classList.add("active");
        return;
      }
      button.classList.remove("active");
    });
  });

  window.addEventListener("load", () => inputs[0].focus());
</script>
{% endblock %}

{% block content %}
<h1>Confirmación OTP</h1>
<div class="otpCheck">
  <div class="container">
    <header>
      <i class="bx bxs-check-shield"></i>
    </header>
    <h4>Enter OTP Code</h4>
    <form action="#">
      <div class="input-field">
        <input type="number" />
        <input type="number" disabled />
        <input type="number" disabled />
        <input type="number" disabled />
      </div>
      <button class="checkButton">Verificar OTP</button>
    </form>
  </div>
</div>
{% endblock %}

ASR1/templates/ASR1/form.html
{% extends "app.html" %}

{% block navRequest %}active{% endblock %}
{% load static %}

{% block content %}
<h1>Formulario de Datos Personales</h1>
<form method="post" class="row g-3 needs-validation">
  {% csrf_token %}
  <div class="col-md-4">
    <label for="id_nombres" class="form-label">Nombres</label>
    <input type="text" class="form-control" id="id_nombres" name="nombres" required>   
  </div>
    <div class="col-md-4">
      <label for="id_apellidos" class="form-label">Apellidos</label>
      <input type="text" class="form-control" id="id_apellidos" name="apellidos" required>
    </div>
    <div class="col-md-3">
      <label for="id_pais" class="form-label">País</label>
      <select class="form-select" id="id_pais" name="pais" required>
        <option value="" disabled>Seleccione un país</option>
        <option value="Colombia">Colombia</option>
      </select>
    </div>          
    <div class="col-md-4">
      <label for="id_ciudad" class="form-label">Ciudad</label>
      <input type="text" class="form-control" id="id_ciudad" name="ciudad" required>
    </div>
    <div class="col-md-4">
      <label for="id_numero" class="form-label">Número</label>
      <div class="input-group has-validation">
        <span class="input-group-text" id="inputGroupPrepend">+57</span>
        <input type="number" class="form-control" id="id_numero" name="numero" aria-describedby="inputGroupPrepend" required>
    </div>
  </div>
    <div class="col-md-3">
      <label for="id_email" class="form-label">Correo</label>
      <input type="email" class="form-control" id="id_email" name="email" required>
    </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        Aceptar términos y condiciones
      </label>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Solicitar TC</button>
  </div>
</form>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Continúa donde lo dejaste</h1>
      </div>
      <div class="modal-body">
        ¡Hola de nuevo! Parece que ya habías empezado a llenar este formulario antes. ¿Quieres retomarlo donde lo dejaste o prefieres empezar de nuevo?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="resetProgressButton" data-bs-dismiss="modal">Empezar de nuevo</button>
        <button type="button" class="btn btn-primary" id="continueProgressButton">Continuar donde quedé</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}<script type="module" src="{% static 'js/ASR3.js' %}"></script>{% endblock js %}

ASR1/templates/ASR1/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banco Los Alpes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand nav-link screenLink" href="#" style="font-size: 2.5rem; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
                <img src="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" alt="Icon" width="100" height="100" class="d-inline-block align-text-mid"> Banco de Los Alpes
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Adquirir TC</a>
                </li>
              </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success">Search</button>
            </form>
        </div>
    </nav>
    <h1>Formulario de Datos Personales</h1>
    <form method="post" class="row g-3 needs-validation">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="id_nombres" class="form-label">Nombres</label>
            <input type="text" class="form-control" id="id_nombres" name="nombres" required>   
          </div>
          <div class="col-md-4">
            <label for="id_apellidos" class="form-label">Apellidos</label>
            <input type="text" class="form-control" id="id_apellidos" name="apellidos" required>
          </div>
          <div class="col-md-3">
            <label for="id_pais" class="form-label">País</label>
            <select class="form-select" id="id_pais" name="pais" required>
              <option value="" disabled>Seleccione un país</option>
              <option value="Colombia">Colombia</option>
            </select>
          </div>          
          <div class="col-md-4">
            <label for="id_ciudad" class="form-label">Ciudad</label>
            <input type="text" class="form-control" id="id_ciudad" name="ciudad" required>
          </div>
          <div class="col-md-4">
              <label for="id_numero" class="form-label">Número</label>
              <div class="input-group has-validation">
                    <span class="input-group-text" id="inputGroupPrepend">+57</span>
                    <input type="number" class="form-control" id="id_numero" name="numero" aria-describedby="inputGroupPrepend" required>
                </div>
          </div>
          <div class="col-md-3">
            <label for="id_email" class="form-label">Correo</label>
            <input type="email" class="form-control" id="id_email" name="email" required>
          </div>
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
            <label class="form-check-label" for="invalidCheck">
              Aceptar términos y condiciones
            </label>
          </div>
        </div>
        <div class="col-12">
          <button class="btn btn-primary" type="submit">Solicitar TC</button>
        </div>
      </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ASR1/templates/ASR1/users.html
{% extends "app.html" %}

{% block navUsers %}active{% endblock %}
{% load static %}

{% block content %}
<h2 class="fs-2 fw-semibold mt-2">Usuarios</h2>
<hr>
<div class="container mb-5">
    <div class="card">
      <table class="table table-hover text-center table-striped">
        <thead class="table">
          <tr>
            <th scope="col">Foto</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Estado</th>
          </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr class="cursor-pointer">
                <th><img src="https://cdn-icons-png.flaticon.com/512/1077/1077012.png" alt="{{ user.nombres }}" width="50" height="50" class="d-inline-block align-text-center"></th>
                <td class="fs-4 align-middle">{{ user.nombres }}</td>
                <td class="fs-4 align-middle">{{ user.apellidos }}</td>
                <td class="fs-4 align-middle">
                    {% if user.state == True %}
                    <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="Información confirmada" width="45" height="45" class="d-inline-block align-text-center">
                    {% else %}
                    <img src="https://cdn-icons-png.flaticon.com/512/4201/4201973.png" alt="Información no confirmada" width="50" height="50" class="d-inline-block align-text-center">
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="container text-center mt-3">
        <div class="row align-items-center">
          <div class="col">
            <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="Información confirmada" width="45" height="45" class="d-inline-block align-text-center">
            <br>
            <p>Información confirmada</p>
          </div>
          <div class="col">
            <img src="https://cdn-icons-png.flaticon.com/512/4201/4201973.png" alt="Información no confirmada" width="50" height="50" class="d-inline-block align-text-center">
            <br>
            <p>Información no confirmada</p>
          </div>
        </div>
      </div>
  </div>
{% endblock content %}

ASR2/templates/ASR2/deployment.html
{% extends "app.html" %}

{% block navDeploy %}active{% endblock %}

{% block content %}
<h2 class="fs-3 fw-bold mb-4 mt-2">Servidores desplegados</h2>
<hr class="mt-1">
<div class="row row-cols-auto justify-content-around">
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/1383/1383395.png" class="card-img-top p-3" alt="Server A" style="width: 70%; margin: auto;">
        <div class="card-body">
          <h5 class="card-title">Server A</h5>
          <div class="d-flex justify-content-center">
            {% if instances.a == 'RUNNING' %}
            <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="state" width="50" height="50">
            {% else %}
            <img src="https://cdn-icons-png.flaticon.com/512/1828/1828843.png" alt="state" width="50" height="50">
            {% endif %}
          </div>
          <p class="card-text text-center">State: {% if instances.a == 'RUNNING' %}Active{% else %}Inactive{% endif %}</p>
          <form method="post" class="row justify-content-center">
            {% csrf_token %}
            <input type="hidden" name="instance" value="banco-alpes-a">
            <button type="submit" class="btn btn-info">{% if instances.a == 'RUNNING' %}Disconnect{% else %}Activate{% endif %}</button>
          </form>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/1383/1383395.png" class="card-img-top p-3" alt="Server B" style="width: 70%; margin: auto;">
        <div class="card-body">
          <h5 class="card-title">Server B</h5>
          <div class="d-flex justify-content-center">
            {% if instances.b == 'RUNNING' %}
            <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="state" width="50" height="50">
            {% else %}
            <img src="https://cdn-icons-png.flaticon.com/512/1828/1828843.png" alt="state" width="50" height="50">
            {% endif %}
          </div>
          <p class="card-text text-center">State: {% if instances.b == 'RUNNING' %}Active{% else %}Inactive{% endif %}</p>
          <form method="post" class="row justify-content-center">
            {% csrf_token %}
            <input type="hidden" name="instance" value="banco-alpes-b">
            <button type="submit" class="btn btn-info">{% if instances.b == 'RUNNING' %}Disconnect{% else %}Activate{% endif %}</button>
          </form>        
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/1383/1383395.png" class="card-img-top p-3" alt="Server C" style="width: 70%; margin: auto;">
        <div class="card-body">
          <h5 class="card-title">Server C</h5>
          <div class="d-flex justify-content-center">
            {% if instances.c == 'RUNNING' %}
            <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="state" width="50" height="50">
            {% else %}
            <img src="https://cdn-icons-png.flaticon.com/512/1828/1828843.png" alt="state" width="50" height="50">
            {% endif %}          </div>
          <p class="card-text text-center">State: {% if instances.c == 'RUNNING' %}Active{% else %}Inactive{% endif %}</p>
          <form method="post" class="row justify-content-center">
            {% csrf_token %}
            <input type="hidden" name="instance" value="banco-alpes-c">
            <button type="submit" class="btn btn-info">{% if instances.c == 'RUNNING' %}Disconnect{% else %}Active{% endif %}</button>
          </form> 
        </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img src="https://cdn-icons-png.flaticon.com/512/1383/1383395.png" class="card-img-top p-3" alt="Server D" style="width: 70%; margin: auto;">
      <div class="card-body">
        <h5 class="card-title">Server D</h5>
        <div class="d-flex justify-content-center">
          {% if instances.d == 'RUNNING' %}
          <img src="https://cdn-icons-png.flaticon.com/512/9426/9426997.png" alt="state" width="50" height="50">
          {% else %}
          <img src="https://cdn-icons-png.flaticon.com/512/1828/1828843.png" alt="state" width="50" height="50">
          {% endif %}        </div>
        <p class="card-text text-center">State: {% if instances.d == 'RUNNING' %}Active{% else %}Inactive{% endif %}</p>
        <form method="post" class="row justify-content-center">
          {% csrf_token %}
          <input type="hidden" name="instance" value="banco-alpes-d">
          <button type="submit" class="btn btn-info">{% if instances.d == 'RUNNING' %}Disconnect{% else %}Activate{% endif %}</button>
        </form> 
      </div>
  </div>
</div>
<h2 class="fs-3 fw-bold mb-4 mt-5">Apagar aplicación</h2>
<hr class="mt-1">
<div class="row justify-content-start">
  <div class="alert alert-danger ms-2" role="alert" style="width: auto;">
    <h4 class="alert-heading">¡Atención!</h4>
    <p>Si apagas la aplicación, todos los servidores se desconectarán.</p>
    <hr>
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="instance" value="turn-off">
      <button type="submit" class="btn btn-danger">Apagar</button>
    </form>
  </div>
</div>
{% endblock %}

BancoAlpes/templates/app.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banco Los Alpes</title>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block css %}{% endblock %}
</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand nav-link navbar-title" href="{% url 'home' %}" style="font-size: 2.5rem; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
              <img src="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" alt="Icon" width="100" height="100" class="d-inline-block align-text-mid"> Banco de Los Alpes
            </a>
            <ul class="navbar-nav d-flex flex-row column-gap-4">
              <li class="nav-item">
                <a class="nav-link {% block navRequest %}{% endblock %}" href="{% url 'request' %}">Adquirir TC</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block navUsers %}{% endblock %}" href="{% url 'users' %}">Usuarios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block navDeploy %}{% endblock %}" href="{% url 'deployment' %}">Despliegue</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success">Search</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid mb-4">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>

BancoAlpes/templates/index.html
{% extends "app.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6 p-5">
      <h2 class="fs-1 fw-bold mt-4">Todo lo que necesitas, en un solo lugar</h2>
      <p class="fs-2">Con nuestra tarjeta de crédito, lleva el control de tus finanzas con facilidad y estilo. ¡Adquiere tu tarjeta de crédito hoy y comienza a disfrutar de todos nuestros beneficios!</p>
      <a href="{% url 'request' %}" class="btn btn-outline-dark">Solicitar</a>
    </div>
    <div class="col-md-6 d-flex justify-content-center">
        {% load static %}
      <img src="https://img.freepik.com/free-vector/banking-industry-concept-illustration_114360-13934.jpg?w=740&t=st=1712971572~exp=1712972172~hmac=e066824cbcc748bb1803a87ab55dea61cbe55da4514114d9dbe47cc7a32af12a" alt="home" class="img-fluid" style="max-width: 100%;">
    </div>
</div>
<h2 class="fs-3 fw-bold mb-4">Conoce más de nuestros productos</h2>
<hr class="mt-1">
<div class="row row-cols-auto justify-content-around">
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" class="card-img-top p-3" alt="Functionality">
        <div class="card-body">
          <h5 class="card-title">Functionality</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" class="card-img-top p-3" alt="Functionality">
        <div class="card-body">
          <h5 class="card-title">Functionality</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="https://cdn-icons-png.flaticon.com/512/8312/8312976.png" class="card-img-top p-3" alt="Functionality">
        <div class="card-body">
          <h5 class="card-title">Functionality</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
</div>
{% endblock %}